---
title: "ggplot1"
author: "Keyanna Davis"
date: "9/26/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
```


## creat the weather data

```{r load_data, cache=TRUE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode_factor (id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

```

```{r}
scatter_plot =
  ggplot(weather_df, aes(x= tmin, y= tmax)) + geom_point()
```


adding color . . . .


```{r}
scatter_plot =
  ggplot(weather_df, aes(x= tmin, y= tmax)) + geom_point(aes(color=name), alpha = .4) +
  geom_smooth(se = FALSE) 
  

```

```{r}
scatter_plot3 =
  ggplot(weather_df, aes(x= tmin, y= tmax)) + geom_point(aes(color=name), alpha = .4) +
  geom_smooth(se = FALSE) +
  facet_grid(~name)

```


```{r}
scatter_plot2 =
  ggplot(weather_df, aes(x= tmin, y= tmax,color=name)) + geom_point() 
```


```{r}
weather_df %>% 
  ggplot(aes(x= date, y= tmax, color =name)) +
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(size = 2, se = FALSE)
```

some extra stuff

```{r}
weather_df %>% 
  ggplot(aes(x= date, y= tmax, color =name)) +
  geom_smooth(size = 2, se = FALSE)
```

##2d density

```{r}
plot_1 = ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_bin2d()
```


##more kinds of plots!!

```{r}
ggplot(weather_df, aes(x = tmax, fill=name)) + 
  geom_histogram() +
  facet_grid(~name)
```


##density plots
```{r}
ggplot(weather_df, aes(x = tmax, fill=name)) + 
  geom_density(alpha=.3) 
 
```

```{r}
weather_df %>% 
  ggplot(aes(x=name, y = tmax)) +
  geom_boxplot()
```

```{r}
weather_df %>% 
  ggplot(aes(x=name, y = tmax)) +
  geom_violin()
```

##ridge plot

```{r}
weather_df %>% 
  ggplot(aes(x=tmax, y = name)) +
  geom_density_ridges()
```

